spring:
  datasource:
    url: jdbc:mysql://ec2-3-37-129-139.ap-northeast-2.compute.amazonaws.com:3306/travel?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: cornerbe
    password: cornerbe0720
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영 시에는 validate or none / 테이블 자동생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.hbm2ddl: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
